[window]
padding.x = 0
padding.y = 0
title = 'Ultimate IDE Application'
dynamic_title = false
opacity = 0.95

[scrolling]
history = 100000

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
