set -g @plugin 'tmux-plugins/tpm'
set -g @plugin '2kabhishek/tmux2k'
set -g @plugin 'wfxr/tmux-fzf-url'

# Set the prefix to Ctrl+a
set -g prefix C-a
set -s escape-time 0
set -g status-interval 5
set -g default-terminal "xterm-256color"

set-window-option -g mode-keys vi

set -g @tmux2k-icons-only true

set -g @tmux2k-theme 'default'
set -g @tmux2k-left-sep "\ue0b8"
set -g @tmux2k-right-sep "\ue0ba"

set -g @tmux2k-red '#ff5189'
set -g @tmux2k-purple '#cf87e8'
set -g @tmux2k-blue '#80a0ff'

set -g @tmux2k-bg-main 'default'
set -g @tmux2k-network-colors 'bg_main red'
set -g @tmux2k-cpu-colors 'bg_main purple'
set -g @tmux2k-ram-colors 'bg_main blue'
set -g @tmux2k-battery-colors 'bg_main purple'
set -g @tmux2k-git-colors 'bg_main red'

set -g @tmux2k-left-plugins "network cpu ram"
set -g @tmux2k-right-plugins "battery git"

set -g @tmux2k-military-time false

# Remove the old prefix
unbind C-b

# Send Ctrl+a to applications by pressing it twice
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."
bind-key m new-window -n spotify_player 'spotify_player'

run '~/.tmux/plugins/tpm/tpm'
