alias docker-compose="docker compose"
alias dce="docker-compose exec"
alias dcu="docker-compose up"
alias dcl="docker-compose logs"
alias dck="docker-compose kill"
alias dcps="docker-compose ps"
alias dc-reset="docker-compose up -d --force-recreate --build"
alias workspace="dce workspace bash"
alias ngrok-tunnel="ngrok http --domain=worthy-radically-worm.ngrok-free.app"
alias v="nvim"

alias dots="ide dots"
alias automotive="ide syntec/automotive"
alias otf="ide otf-shopify"
alias finder="nautilus --browser"
