alias dce="docker-compose exec"
alias dcu="docker-compose up"
alias dcl="docker-compose logs"
alias dck="docker-compose kill"
alias dcps="docker-compose ps"
alias dc-reset="docker-compose up -d --force-recreate --build"
alias workspace="dce workspace bash"
alias ngrok-tunnel="ngrok http --domain=worthy-radically-worm.ngrok-free.app"
alias v="nvim"

alias automotive="tmux new-session -A -s automotive -c /home/maartenn/projects/syntec/automotive"
alias otf="tmux new-session -A -s otf -c /home/maartenn/projects/otf-shopify"
